version: 2
jobs:
  build-go1.14:
    docker:
      - image: golang:1.14
    working_directory: /go/src/github.com/micromdm/squirrel
    steps: &steps
      - checkout
      - run: make

workflows:
  version: 2
  build:
    jobs:
      - build-go1.14
